url: "https://mgarratt.uk"
baseurl: "/"
title: "Engineering Manager"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENCE.md
  - Makefile
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - README.md
  - node_modules
encoding: "utf-8"

plugins:
  - jekyll-postcss

postcss:
  cache: false